// <auto-generated />
namespace MVC_DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class heading1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(heading1));
        
        string IMigrationMetadata.Id
        {
            get { return "202507011053005_heading1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
